### ISSUE TITLE
lokka-transport-http

### ISSUE THREAD

**Issue by mvanlonden** [tehsis/webtaskio-canirequire#121]
Can't use lokka without this dep. Please add it

**Comment by glennblock** [comment]
@mvanlonden have you tried putting in your package.json. If you are using the latest version of our cli we now support all modules (barring a few exceptions). You can read about this here: https://webtask.io/docs/modules

**Comment by glennblock** [comment]
We don't have a good story for modules YET via the web-based editor, but it is coming very soon.

**Comment by lewisblackwood** [comment]
@glennblock I've tried to including this module in the package.json. 

I've then run:

`wt-bundle lokka.js --output build/lokka.js -m`
`wt create build/lokka.js`


However, the minified result is around 320kb - the error is:

`Uncaught error:  Request body size exceeds 122880`
`Error: Payload Too Large`

Any ideas? I'm using `wt-cli@6.1.0`.

**Comment by glennblock** [comment]
You don't need to bundle anymore. We now will install any module dynamically from npm. Just put it in a package.json and publish your task normally. wt cli should pick up the the dependencies and grab them via our new npm builder.

**Comment by glennblock** [comment]
That is assuming you have have the latest cli....

**Comment by glennblock** [comment]
Take a look at the modules link I shared above (which was recently updated) as it describes the new support for package.json and dynamically installing modules.

**Comment by glennblock** [comment]
Don't bundle. Just use the cli and have a package.json with your module. We
have recently added full support for npm assuming you have the latest cli.
You can read more here: https://webtask.io/docs/modules

**Comment by lewisblackwood** [comment]
My bad, I was following old documentation! That worked. Thanks for you help @glennblock !

**Comment by glennblock** [comment]
No problem! We haven't broadcast this outside of the Webtask slack / blogged on this yet because we are waiting till we get editor support to just do one blog post.
