### ISSUE TITLE
apollo-server, express-graphql, graphql

### ISSUE THREAD

**Issue by bkniffler** [tehsis/webtaskio-canirequire#16]
Hi, 
Webtask seems very well suited for creating APIs, but graphql related libs are missing. Could you add these? apollo-server, express-graphql, graphql

Thanks!

**Comment by glennblock** [comment]
@bkniffler thanks for submitting this. We won't be able to add these right now on webtask.io because they have sibling dependencies and we need to do some work there. We can support graphql today in our private SAAS offering.

**Comment by freiksenet** [comment]
@glennblock What do you mean by 'sibling dependencies'? Peer dependencies? GraphQL itself doesn't seem to have any, I wonder if you could at least add the GraphQL lib itself.

Thanks!

**Comment by glennblock** [comment]
We have recently added full support for npm modules via package.json assuming you have the latest cli. You can read more here: https://webtask.io/docs/modules

**Comment by glennblock** [comment]
Oh hai @freiksenet !
