### ISSUE TITLE
react

### ISSUE THREAD

**Issue by luisrudge** [tehsis/webtaskio-canirequire#18]
rendering components in the server would be awesome

**Comment by luisrudge** [comment]
you need react-dom as well.
https://facebook.github.io/react/docs/environments.html

**Comment by glennblock** [comment]
It doesn't like we'll be able to add react-dom right now (we tried) as it has a sibling dependency on react and we don't have good support for sibling dependencies _yet_. React is there though.

**Comment by luisrudge** [comment]
not much we can do with react only :( You need react-dom to render components as a string

**Comment by glennblock** [comment]
We have recently added full support for npm modules via package.json assuming you have the latest cli. You can read more here: https://webtask.io/docs/modules
