### ISSUE TITLE
I need html-pdf so that I can generate PDF receipts on the fly for my commerce site

### ISSUE THREAD

**Issue by jhnsntmthy** [tehsis/webtaskio-canirequire#28]
I would like to have https://www.npmjs.com/package/html-pdf which is based on phantomjs (a big package in its own right) to generate a PDF from incoming data and an HTML file. Would love to be able to do this on Webtask.

I found this article about how to do it on Lambda, and I've been playing around with Lambda lately, but I have watched a lot of Webtask videos from the Serverless Conf (primarily Joe Emison) and Webtask is great to get up and running with. 

OR...
Is there a way I can bundle these packages to use them and upload them with the task? I just haven't found it in the documentation yet before I found this link to GH issues.

**Comment by glennblock** [comment]
Hi @jhnsntmthy, we cannot support this today on webtask.io as we don't support phantom. We do support phantomjs in our private instances though and so `html-pdf` could also be used. 

`pdf-kit` is available though which can be used for PDF generation. Would that work for you?
