### ISSUE TITLE
Stripe v.4

### ISSUE THREAD

**Issue by brianjaystanley** [tehsis/webtaskio-canirequire#42]
The current version of Stripe is 4.14.0. The only version on webtask.io is 3.3.4. The Stripe API has changed since then, such that using the `stripe.subscriptions.create` API doesn't work (v3 uses `stripe.customerSubscriptions`). Stripe doesn't appear to maintain any documentation for v3 (that I can find).

Can we get a newer version of Stripe?

**Comment by glennblock** [comment]
Hi Brian, this is live now.
