### ISSUE TITLE
gm - graphicsmagick

### ISSUE THREAD

**Issue by vladgolubev** [tehsis/webtaskio-canirequire#5]
Is it possible to require npm module `gm` - which is a wrapper around graphicsmagick ?

**Comment by ggoodman** [comment]
@vladgolubev we do not have `graphicsmagick` installed on the platform. I do not think that we want to encourage memory/cpu-intensive operations on the webtask platform for the time being.

**Comment by vladgolubev** [comment]
@ggoodman makes sense. Maybe worth mentioning somewhere in the docs/README? Or it is already and I missed?
