### ISSUE TITLE
Lokka

### ISSUE THREAD

**Issue by onlymejosh** [tehsis/webtaskio-canirequire#58]
I'm working with graphQL and am using Lokka for the transport. Could you add the following libraries please?

```
"lokka": "^1.7.0",
"lokka-transport-http": "^1.6.1",
```

**Comment by adrianocola** [comment]
I'm also trying to use Lokka, but the module "lokka-transport-http" is missing!

**Comment by glennblock** [comment]
We have recently added full support for npm modules via package.json assuming you have the latest cli. You can read more here: https://webtask.io/docs/modules
