### ISSUE TITLE
bunyan-loggly, node-logentries

### ISSUE THREAD

**Issue by jbrody1** [tehsis/webtaskio-canirequire#66]
Logging as a service:

https://www.npmjs.com/package/winston-papertrail
https://www.npmjs.com/package/bunyan-loggly
https://www.npmjs.com/package/node-logentries

**Comment by glennblock** [comment]
We have recently added full support for npm modules via package.json assuming you have the latest cli. You can read more here: https://webtask.io/docs/modules
