### ISSUE TITLE
Request: Neo4j Bolt Driver

### ISSUE THREAD

**Issue by dmk255** [tehsis/webtaskio-canirequire#82]
Hello!

I would love to be able to use the neo4j javascript driver. I've included the github link below. It is also on npm. This is a library for connecting to neo4j databases. 

https://github.com/neo4j/neo4j-javascript-driver

Best,
Daniel

**Comment by glennblock** [comment]
We have recently added full support for npm modules via package.json assuming you have the latest cli. You can read more here: https://webtask.io/docs/modules
