### ISSUE TITLE
SSHA512 comparison

### ISSUE THREAD

**Issue by atpugnitin** [tehsis/webtaskio-canirequire#9]
Migrating from LDAP requires some SSHA comparison. Can use https://www.npmjs.com/package/dovehash

**Comment by atpugnitin** [comment]
I can see dovehash included in https://tehsis.github.io/webtaskio-canirequire 
To use it, do I need to instantiate a variable or is there a global variable available.

**Comment by glennblock** [comment]
Just use `require("dovehash")` and it should be there.
