### ISSUE TITLE
nodemailer 3.x

### ISSUE THREAD

**Issue by tjaartvdwalt** [tehsis/webtaskio-canirequire#94]
I would like to use nodemailer with OAuth authentication. Unfortunately with the currently available version `2.3.0`, you need to install [xoauth2](https://www.npmjs.com/package/xoauth2) as a dependency.

It seems that from version 3 this dependency has been removed, so I would request either an updated nodemailer, or xoauth2 :)

**Comment by glennblock** [comment]
We have recently added full support for npm modules via package.json assuming you have the latest cli. You can read more here: https://webtask.io/docs/modules
