### ISSUE TITLE
Support Meshblu, open-source IoT machine-to-machine messaging system. 

### ISSUE THREAD

**Issue by iotrentil** [tehsis/webtaskio-canirequire#95]
Meshblu is open-source IoT m2m messaging platform and Octoblu is operating stable cloud (https://www.octoblu.com)

They provides node module for connecting meshblu HTTP connection
https://github.com/octoblu/node-meshblu-http

I'd like to use node-meshblu-http to implement Hook at Auto0.

**Comment by glennblock** [comment]
We have recently added full support for npm modules via package.json assuming you have the latest cli. You can read more here: https://webtask.io/docs/modules
