### ISSUE TITLE
tinify - png compression API

### ISSUE THREAD

**Issue by rosswaycaster** [tehsis/webtaskio-canirequire#98]
Node.js client for the Tinify API, used for TinyPNG and TinyJPG. Tinify compresses your images intelligently. Read more at http://tinify.com.

https://tinypng.com/developers/reference/nodejs

https://www.npmjs.com/package/tinify

**Comment by glennblock** [comment]
We have recently added full support for npm modules via package.json assuming you have the latest cli. You can read more here: https://webtask.io/docs/modules
